package gamerix;


import java.beans.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp 1
 */
public class loginpage extends javax.swing.JFrame {

   Connection con=null;
   PreparedStatement pst=null;
	Statement s;
	ResultSet rs=null;
    public loginpage() throws ClassNotFoundException, SQLException {
        initComponents();
     
			
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
		setExtendedState(java.awt.Frame.MAXIMIZED_BOTH);

        username = new javax.swing.JTextField();
        loginbtn = new javax.swing.JButton();
        pass = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        username.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        username.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        getContentPane().add(username);
        username.setBounds(270, 150, 150, 30);

        loginbtn.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        loginbtn.setText("login");
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        getContentPane().add(loginbtn);
        loginbtn.setBounds(190, 260, 150, 40);
        getContentPane().add(pass);
        pass.setBounds(270, 200, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/loginpage.jpg"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(4, 4, 610, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MousePressed

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
        String un=username.getText();
        String pw=pass.getText();
        con=MySqlConnect.ConnectDB();
        String Sql="Select * from login where name=? and password=?";
        try
        {
            pst=con.prepareStatement(Sql);
            pst.setString(1,un);
            pst.setString(2,pw);
            rs=pst.executeQuery(); if(rs.next())
            {
                Choice c=new Choice();
                c.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null,"invalid");
            }
        }catch(Exception e)
        {}

    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) throws ClassNotFoundException, SQLException {
       
           
             
                    new loginpage().setVisible(true);
           
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton loginbtn;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables

}